name: Deploy to vercel

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: committing to vercel
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
