on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: I run on PR comment
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    outputs:
      # opt_in is true if the comment body contains the string "!test"
      opt_in: ${{ contains(github.event.comment.body, '!test') }}
      merge: ${{ contains(github.event.comment.body, '!!test!!') }}
      ref: ${{ github.event.issue.pull_request.head.ref }}

    steps:
      # print if they opted in or not
      - run: |
          echo "opt_in: ${{ contains(github.event.comment.body, '!test') }}"
          echo "pr_url: ${{ github.event.issue.pull_request.url }}"
        env:
          NUMBER: ${{ github.event.issue.number }}

  checkout-repo:
    name: they said !test!

    # This job only runs if the previous job opted in
    needs: pr_commented
    if: needs.pr_commented.outputs.opt_in == 'true'

    runs-on: ubuntu-latest
    environment: committing to vercel

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}
      - name: install dependencies
        run: npm install
      - name: run cypress
        uses: cypress-io/github-action@v4
        with:
          start: npm run dev
      - name: push to vercel
        uses: amondnet/vercel-action@v20
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}

    # uses: phil-loops/testing-cypress/.github/workflows/run-cypress-checks.yml@main

  # commit-to-vercel:
  #   name: Push to Vercel
  #   needs: checkout-repo
  #   if: needs.pr_commented.outputs.merge == 'true'
  #   uses: phil-loops/testing-cypress/.github/workflows/deploy-to-vercel.yml@main

  #   secrets: inherit
  # #   steps:
  # #     - uses: actions/checkout@v3
  # #       with:
  # #         ref: ${{ github.event.issue.pull_request.head.ref }}
  #         repository: ${{ github.event.issue.pull_request.head.repo.full_name }}

  # run-cypress:
  #   name: run cypress
  #   needs: checkout-repo
  #   uses: phil-loops/testing-cypress/.github/workflows/run-cypress-checks.yml@main

  # # https://github.com/actions/checkout/issues/331#issuecomment-707103442
  # runs-on: ubuntu-latest
  # steps:
  #   - uses: actions/github-script@v3
  #     id: get-pr
  #     with:
  #       script: |
  #         const request = {
  #           owner: context.repo.owner,
  #           repo: context.repo.repo,
  #           pull_number: context.issue.number
  #         }
  #         core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
  #         try {
  #           const result = await github.pulls.get(request)
  #           return result.data
  #         } catch (err) {
  #           core.setFailed(`Request failed with error ${err}`)
  #         }
  #   - uses: actions/checkout@v2
  #     with:
  #       repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
  #       ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }}
  #   # - uses: phil-loops/testingt-cypress/.github/workflows/run-cypress-checks.yml@main
