name: Run Cypress checks

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - uses: cypress-io/github-action@v4
        with:
          start: npm run dev
