name: Compile + Lint

on:
  push:
    branches:
      - main

jobs:
  chekcout:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

  push-to-deployment-branch:
    needs: [chekcout]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions[bot]"
      - run: timestamp=$(date -u)
      - run: git commit -m "Bot published at ${timestamp}" || exit 0
      - run: git pull --rebase vercel-deployment
      - run: git push upstream vercel-deployment
