name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "vercel-deployment"
      - name: Commit report
        run: |
          git reset --hard origin/main
          git push origin vercel-deployment --force
