name: Push commit
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  report:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Loopsbot'
          git config --global user.email 'help@loops.so'
          git checkout vercel-deployment
          git reset main --hard
          git push origin vercel-deployment --force
